
#!/bin/bash
#$ -pe smp 16
#$ -q all.q
#$ -m bea
#$ -M zachary-gilliam@uiowa.edu
#$ -o /Shared/vosslabhpc/symposia/cpsy-25/data/freesurfer_7.1/better/out
#$ -e /Shared/vosslabhpc/symposia/cpsy-25/data/freesurfer_7.1/better/err

mkdir -p /Shared/vosslabhpc/symposia/cpsy-25/data/freesurfer_7.1/better/sub-GE120047

OMP_NUM_THREADS=10
export FS_LICENSE=/Shared/vosslabhpc/Projects/BikeExtend/3-Experiment/2-Data/BIDS/derivatives/code/freesurfer_7.1/job_scripts/license.txt
singularity exec --cleanenv -B /Shared/vosslabhpc/symposia/cpsy-25/gitrepo/fsf/wmh_synthseg_latest.sif /Shared/vosslabhpc/symposia/cpsy-25/gitrepo/fsf/wmh_synthseg_latest.sif python /app/WMHSynthSeg/inference.py --i /Shared/vosslabhpc/Projects/BETTER/3-Experiment/2-data/bids/derivatives/freesurfer/sub-GE120047/mri/brain.mgz --o /Shared/vosslabhpc/symposia/cpsy-25/data/freesurfer_7.1/better/sub-GE120047/sub-GE120047_synth.nii.gz --threads 10 --save_lesion_probabilities --csv_vols /Shared/vosslabhpc/symposia/cpsy-25/data/freesurfer_7.1/better/sub-GE120047/sub-GE120047_synth.csv 
